### ISSUE TITLE
Any updates on when this will be released?

### ISSUE THREAD

**Issue by evanw555** [jaba9531/schedule-bot#1]
I currently have an active server with scheduling issues and this would really help us. I'm looking forward to when this gets released!

**Comment by jaba9531** [comment]
Hi Evan, currently my day job is taking up most of my coding stamina but I should be back at it soon! My local branch is further ahead; I can push it up later today. It should give you a better idea of where things are at.

**Comment by evanw555** [comment]
Sounds good, thanks for the update.
